# Generated by Django 6.0.3 on 2026-04-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='oficinas/logos/'),
        ),
    ]
