# Generated by Django 6.0.3 on 2026-04-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='descricao_problema',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='combustivel_tipo',
            field=models.CharField(choices=[('E', 'Etanol'), ('G', 'Gasolina'), ('F', 'Flex'), ('D', 'Diesel')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='conclusao_tecnica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='km_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_injecao_acesa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='nivel_combustivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='previsao_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='servico_solicitado',
            field=models.TextField(default=1, help_text='Exatamente como o cliente relatou'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tem_abs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tem_documento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='transmissao',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automática')], default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('entrada_ok', models.BooleanField(default=False)),
                ('saida_ok', models.BooleanField(default=False)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_checklist', to='operations.ordemservico')),
            ],
        ),
    ]
