# Generated by Django 6.0.3 on 2026-04-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_ordemservico_descricao_problema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='capa_banco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='capa_protecao_frontal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='chassi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='filme_cambio_freio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='filme_volante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='horario_orcamento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='motor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='onde_nos_conheceu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='portas',
            field=models.CharField(choices=[('2', '2 Portas'), ('4', '4 Portas')], default='4', max_length=10),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='ultima_troca_oleo_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='ultima_troca_oleo_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='versao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='transmissao',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatica', 'Automática')], default='Manual', max_length=20),
        ),
    ]
