# Generated by Django 6.0.3 on 2026-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_ordemservico_capa_banco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='entrada_ok',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='saida_ok',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='fase',
            field=models.CharField(choices=[('entrada', 'ENTRADA'), ('saida', 'SAÍDA')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('sim', 'SIM'), ('nao', 'NÃO')], default='pendente', max_length=10),
        ),
    ]
