# Generated by Django 6.0.3 on 2026-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_checklistitem_entrada_ok_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='chassi',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='conclusao_tecnica',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='nivel_combustivel',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='previsao_entrega',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='ultima_troca_oleo_data',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='ultima_troca_oleo_km',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='versao',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(choices=[('Etanol', 'Etanol'), ('Gasolina', 'Gasolina'), ('Flex', 'Flex'), ('Diesel', 'Diesel')], default='Flex', max_length=20),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='motor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='portas',
            field=models.CharField(choices=[('2', '2 Portas'), ('4', '4 Portas')], default='4', max_length=10),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tem_abs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='transmissao',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatica', 'Automática')], default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='versao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='fase',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(default='p', max_length=5),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='combustivel_tipo',
            field=models.CharField(choices=[('Flex', 'Flex'), ('Gasolina', 'Gasolina'), ('Etanol', 'Etanol'), ('Diesel', 'Diesel')], default='Flex', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='onde_nos_conheceu',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='servico_solicitado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(default='aberta', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='whatsapp',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.CharField(max_length=20),
        ),
    ]
