# Generated by Django 6.0.3 on 2026-04-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_remove_ordemservico_chassi_and_more'),
        ('workshops', '0003_alter_perfilusuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, verbose_name='Placa'),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(fields=('oficina', 'placa'), name='unique_placa_por_oficina'),
        ),
    ]
