# Generated by Django 6.0.3 on 2026-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_veiculo_placa_veiculo_unique_placa_por_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='assinatura_cliente_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='mapa_avarias_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='nivel_combustivel',
            field=models.IntegerField(default=0),
        ),
    ]
