# Generated by Django 6.0.3 on 2026-04-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_ordemservico_assinatura_cliente_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='ultima_troca_oleo_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='ultima_troca_oleo_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
