# Generated by Django 6.0.3 on 2026-04-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_ordemservico_ultima_troca_oleo_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='conclusao_tecnica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
