# Generated by Django 6.0.3 on 2026-04-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_ordemservico_conclusao_tecnica'),
        ('workshops', '0004_mecanico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='mecanico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.mecanico'),
        ),
    ]
